### ISSUE TITLE
Etabs_Toolkit: Bar releases fail to push to Etabs

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/ETABS_Toolkit#156]
Errors when pushing bar releases to Etabs. Needs investigating and fixing

**Comment by enarhi** [comment]
@IsakNaslundBh sending releases to etabs today and came across this, looks like it is just due to sending releases that are unstable. (Excerpt below) Works as expected when stable releases are sent through. Perhaps a more specific error should be added when unstable releases are sent in order to close this issue?

**Comment by enarhi** [comment]
@IsakNaslundBh adding to this, looks like the releases are not necessarily applied to the right side. This is due to ETABS sometimes flipping members upon creation (looks like ETABS enforces left-right frames even though the API fails to mention this.) I am creating a separate issue for bar start/end node management as that will have negative follow up effects on other directional properties as well.

**Comment by IsakNaslundBh** [comment]
To link the issues, This can be looked at in tandem with https://github.com/BHoM/ETABS_Toolkit/issues/232
