### ISSUE TITLE
ETABS_Toolkit: Stack overflow when pushing non-implemented section

### ISSUE THREAD

**Issue by kThorsager** [BHoM/ETABS_Toolkit#213]
#### Description:
Tried pushing a `GenerilisedTsectionProfile` and it closed down my Rhino. tried again while debugging and found a stack overflow when the section is created.
Did a small fix which avoided the total crash of Rhino.
![Fix](https://user-images.githubusercontent.com/53530468/66121735-ca84b400-e5d5-11e9-8310-5e8a26ca754b.PNG)

#### How to replicate:
push something containing this `BH.oM.Geometry.ShapeProfiles.GeneralisedTSectionProfile`

#### Expected Behaviour after
The same as in my fix and preferably that the section can be pushed as well.
If my fix looks good I can make the PR

**Comment by JosefTaylor** [comment]
Ah, this is the same as my recent problem with a few sections, the fix for which was to add an empty method SetProperty() that accepted that profile type and threw an error. This is probably better long term, and means we can remove all those empty methods for unsupported profiles, replacing them with a single error message in ISetProperty().
